# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

strategy:
    matrix:
       linux:
          imageName: "ubuntu-16.04"
       mac:
          imageName: "macos-10.13"
       windows:
          imageName: "vs2017-win2016"
    maxParallel: 3

pool:
  vmImage: $(imageName)

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
# Linux
- bash: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    ls
    sudo apt update
    sudo apt upgrade
  condition: eq( variables['Agent.OS'], 'Linux') 
  displayName: 'Install Pre-Request in Linux'
- bash: |
        git clone https://gitlab.com/libeigen/eigen.git
        cd eigen
        mkdir build
        cd build
        cmake ..
        make install
        cd ../..

  condition: eq( variables['Agent.OS'], 'Linux') 
  displayName: 'Install Pre-Request in Linux'

- bash: |
     git clone https://github.com/strasdat/Sophus.git
     cd Sophus
     mkdir build
     cd build
     cmake ..
     make install
     cd ../..
  condition: eq( variables['Agent.OS'], 'Linux') 
  displayName: 'Install Sophus in Linux'

# macOS
- bash: |
     brew install git cmake opencv eigen cgal libomp
     git clone https://github.com/strasdat/Sophus.git
     cd Sophus
     mkdir build
     cd build
     cmake ..
     make install
     cd ../..
     git clone https://github.com/google/googletest.git
     cd googletest
     cmake .
     make install
     cd ..
  condition: eq( variables['Agent.OS'], 'Darwin')
  displayName: 'Pre-request MacOS'

- bash: |
     mkdir build
     cd build
     cmake ..
     make

  condition: eq( variables['Agent.OS'], 'Darwin')
  displayName: 'Compile In MacOS'

- bash: |
     ./test.main

  condition: eq( variables['Agent.OS'], 'Darwin')
  displayName: 'Run Test'



# Windows
- powershell: |
      echo "I am Windows"
  condition: eq( variables['Agent.OS'], 'Windows_NT')

