# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

strategy:
    matrix:
       linux:
          imageName: "ubuntu-16.04"
       mac:
          imageName: "macos-10.13"
       windows:
          imageName: "vs2017-win2016"
    maxParallel: 3

pool:
  vmImage: $(imageName)

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
# Linux
- bash: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    ls
    sudo apt install -y cmake
  condition: eq( variables['Agent.OS'], 'Linux') 
  displayName: 'Run a multi-line script'
 
# macOS
- bash: |
     brew install cmake
  condition: eq( variables['Agent.OS'], 'Darwin')

# Windows
- powershell: |
      echo "I am Windows"
  condition: eq( variables['Agent.OS'], 'Windows_NT')

